- Generated on CADE machines

Weird behavior:
- Reproduce the problem on verify.py but not in separate browser

What has been tried:
- Tried reproducing the bug in local browser (http server on CADE) -> NO BUG
- Reproduce bug with verify.py -> BUG
- Reproduce bug with verify.py, set debugger and step line by line -> BUG
- Try in browser with different window dimensions -> NO BUG
- Try in browser without dev tools open -> NO BUG